# (c) Copyright IBM Corp. 2017.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: zspark202/loz-scala-wb
    container_name: ${WORKBOOK_NAME}
    command: >
      bash -c "start-notebook.sh --port=${WORKBOOK_PORT} --NotebookApp.token='' ${WORKBOOK_DEBUG}"
    network_mode: "host"
    environment:
      IBM_JAVA_OPTIONS: "-Dlog4j.configurationFile=/home/jovyan/work/log4j.properties -Duser.name=${SPARK_USER}"
      JVM_OPT: "-Duser.name=${SPARK_USER}"
      SPARK_USER: ${SPARK_USER}
      HADOOP_USER_NAME: ""
      SPARK_LOCAL_IP: ${WORKBOOK_IP}
      SPARK_OPTS: "--master=spark://${SPARK_HOST}:${SPARK_PORT} --conf spark.cores.max=${SPARK_CPUS} --conf spark.executor.memory=${SPARK_MEM}"
#      USE_HTTPS: "yes"
#      PASSWORD: ${PASSWORD}
    volumes:
      - "work:/home/jovyan/work"
volumes:
  work:
    external:
      name: ${WORKBOOK_VOLUME}
